/*
 * Copyright (C) 2016 Jean.
 */

package fabrisoft.view;

import javax.swing.JButton;

/**
 *
 * @author Jean
 */
public abstract class BaseForm extends javax.swing.JDialog {

    /**
     * Creates new form FrameCadastroView
     */
    public BaseForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    private char acao;
    public abstract String getNome();
    public static final char INCLUINDO='I',ALTERANDO='A',VISUALIZANDO='V';
    public void incluir(){
        btnCancelar.setEnabled(true);
        btnNovo.setEnabled(false);
        btnGravar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnProcurar.setEnabled(false);
        acao=INCLUINDO;
    }
    public void cancelar(){
        btnCancelar.setEnabled(false);
        btnGravar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnProcurar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnNovo.setEnabled(true);
    }
    public void alterar(){
        btnCancelar.setEnabled(true);
        btnNovo.setEnabled(false);
        btnGravar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnProcurar.setEnabled(false);
        acao=ALTERANDO;
    }
    public void visualizar(){
        btnCancelar.setEnabled(false);
        btnGravar.setEnabled(false);
        btnExcluir.setEnabled(true);
        btnProcurar.setEnabled(true);
        btnAlterar.setEnabled(true);
        btnNovo.setEnabled(true);
        acao=VISUALIZANDO;
    }

    public char getAcao() {
        return acao;
    }
    
    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JButton getBtnExcluir() {
        return btnExcluir;
    }

    public JButton getBtnGravar() {
        return btnGravar;
    }

    public JButton getBtnNovo() {
        return btnNovo;
    }

    public JButton getBtnProcurar() {
        return btnProcurar;
    }

    public JButton getBtnAlterar() {
        return btnAlterar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnProcurar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnNovo.setText("Novo");
        jPanel1.add(btnNovo);

        btnAlterar.setText("Alterar");
        jPanel1.add(btnAlterar);

        btnGravar.setText("Gravar");
        jPanel1.add(btnGravar);

        btnProcurar.setText("Procurar");
        jPanel1.add(btnProcurar);

        btnExcluir.setText("Excluir");
        jPanel1.add(btnExcluir);

        btnCancelar.setText("Cancelar");
        jPanel1.add(btnCancelar);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        setSize(new java.awt.Dimension(619, 471));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnProcurar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
